version: 0.0
os: linux
files:
  - source: ./app
    destination: /tmp/app
hooks:
  BeforeInstall:
    - location: ./deploy/install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: ./deploy/configure.sh
      timeout: 60
      runas: root
  ValidateService:
    - location: ./deploy/validate.sh
      timeout: 60
      runas: root
  ApplicationStart:
    - location: ./deploy/start.sh
      timeout: 60
      runas: root
  ApplicationStop:
    - location: ./scripts/stop_server.sh
      timeout: 60
      runas: root

